### ISSUE TITLE
Business-Partners Logo missing 

### ISSUE THREAD

**Issue by Mika215** [Mika215/hyf-website-group-2#91]
Hey Group,
i have tried to implement  two related issues which are refered as "Become partner button" Issue = https://github.com/Mika215/hyf-website-group-2/issues/42#
and " Business-partners" class issue = https://github.com/Mika215/hyf-website-group-2/issues/43# 
and it has been reviewed by @otagi and then finaly aproved and closed by @alinamarasca 

However, even though i can see the changes in my computer when i open the code with **Live server viwer** 
i couldn't still view the same changes in the [Repo GitHub page]( https://mika215.github.io/hyf-website-group-2/)
Could some of you share me your technical advice why it is not functioning properly?

Many thanks! 🙏 

Below i have attached you screen shoots of both pages

![Image from my live server](https://user-images.githubusercontent.com/75224973/108591705-597ca280-736a-11eb-9bc8-0ab1088e0261.png)

![Image from the repo GitHub page](https://user-images.githubusercontent.com/75224973/108591641-0f93bc80-736a-11eb-90c2-6e3295591b49.png)

**Comment by otagi** [comment]
The partner images don't show on GitHub Pages because of the `src` path you used:

```html
<img alt="" src="/images/1-1-print-smple.svg" class="business-partners-logo">
```

The path is relative to the root of the website, because it starts with a `/`. That means the web server will look for an `images` folder there: `https://mika215.github.io/images/1-1-print-smple.svg`.

On GitHub Pages, the difference is that your website URLs have an additional `hyf-website-group-2` folder in the middle.

What you want is a path relative to the current folder, without the leading `/`: 

```html
<img alt="" src="images/1-1-print-smple.svg" class="business-partners-logo">
```

The web server will append that path to whichever subfolder your site is in, to have a final URL like this: `https://mika215.github.io/hyf-website-group-2/images/1-1-print-smple.svg`.

[HTML file paths on W3Schools](https://www.w3schools.com/Html/html_filepaths.asp)

PS: Be sure to always add an `alt` text to your images, like the name of the partner in this case. That way, even if the images don't load, you will at least see that text. And it makes the website more accessible for blind people.
